= eXXcellent programming challenge

Solution by Dominik Burgdörfer.

== Getting started

=== Install Java
For this project, the Java Development Kit 17 or above is required. You can download it from https://adoptopenjdk.net/.

=== Directly clone the repository

```
git clone https://github.com/domachine/programming-challenge.git
```

=== Switch to the branch of the challenge assigned
```
cd programming-challenge
git switch challenge-weatherdata
```

=== Building and running
The project scaffolds provides a Maven `pom.xml` as starting
point. You should be able to start with any IDE or text editor
you are convenient with.

After installing Maven 3.x you should be able to

Build & test your project::
    `mvn verify`

Then to run the main class _de.exxcellent.challenge.App_::
    - Weather task: `mvn exec:java -Dexec.args="--weather weather.csv"`
    - Football task: `mvn exec:java -Dexec.args="--football football.csv"`

To remove the compilation output::
    `mvn clean`

Or use your IDE functionality::
    to run & debug you program.
